# Generated by Django 4.2.7 on 2023-12-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodl',
            name='imag',
            field=models.ImageField(blank=True, null=True, upload_to='saveimage'),
        ),
    ]
